### ISSUE TITLE
Deprecate old templates

### ISSUE THREAD

**Issue by vvo** [algolia/create-instantsearch-app#148]
## The problem

We currently have two ways to give templates:
- https://github.com/algolia/instantsearch-templates#codesandbox-links
- https://github.com/algolia/create-instantsearch-app#previews

So it's not clear which one to use in support

## Solution

Since the later provide almost the same functionality as the former, we could deprecate instantsearch templates completely and link back to create-instantsearch-app previews/readme.

What do you think?

**Comment by francoischalifour** [comment]
Indeed, I created an issue on [algolia/instantsearch-templates](https://github.com/algolia/instantsearch-templates) a few days ago ([algolia/instantsearch-templates#155](https://github.com/algolia/instantsearch-templates)).

We can explicitly deprecate `instantsearch-templates`, archive the repository and remove the Renovate integration. I was initially waiting for your approval.

**Comment by vvo** [comment]
It's all good for me (I was not watching the repository anymore).

If you need my help on any repo, just @ mention me and Ill answer, otherwise there are some repos I am no more watching. You are the new owner :)

You have admin rights, you can go for it now

**Comment by francoischalifour** [comment]
Closed in algolia/instantsearch-templates#139.
