### ISSUE TITLE
Provide multiple fields for the main attribute?

### ISSUE THREAD

**Issue by bobylito** [algolia/create-instantsearch-app#151]
## The problem

Now we can provide one field. What about we could select more than one?

## Solution

Provide a multi select in the CLI

**Comment by francoischalifour** [comment]
- How would you see the command-line menu?
- How would you display the attributes in the default app? (all `div`s?)

**Comment by Haroenv** [comment]
first one h1, others p IMO

Command line menu could be like `yarn update-interactive`

**Comment by francoischalifour** [comment]
I like the idea of [checkboxes](https://github.com/SBoudrias/Inquirer.js/#checkbox---type-checkbox) as you suggested!

Having multiple `h1`s is semantically incorrect though. What about something like this markup for a hit?

```html
<section>
  <header>
    <h3>{{{_highlightResult.name.value}}}</h3>
  </header>
  <p>{{{_highlightResult.description.value}}}</p>
</section>
```

The first attribute in the interactive list would go in the `header` as a `h3` while the others are `p`s.

**Comment by Haroenv** [comment]
`<h1>` is fine in `<article>`, it restart the count

**Comment by francoischalifour** [comment]
Oh that's brilliant!

Note that we might have to release this in a new major version since it introduces a public API change (`mainAttribute` → `attributesToDisplay`).

**Comment by bobylito** [comment]
All you said are good for me (major + article and h1) 👍
