### ISSUE TITLE
Add an option to deploy to jsFiddle or codeSandbox

### ISSUE THREAD

**Issue by bobylito** [algolia/create-instantsearch-app#2]

**Comment by francoischalifour** [comment]
Do we still want this feature in the templates scripts?

It's useful but CodeSandbox already provides [a CLI](https://github.com/codesandbox-app/codesandbox-importers/tree/master/packages/cli) to deploy the project.

```
codesandbox .
```

**Comment by bobylito** [comment]
What about adding in the documentation a part in which you explain how to host your app?

**Comment by francoischalifour** [comment]
I'm not sure it's worth having a specific section on this but I like the idea.

A FAQ section could be helpful in the README – with a special section on "How to deploy my application".

Questions that come to my mind right now:

- How to use my own template with Create InstantSearch App
- How to deploy my application

**Comment by bobylito** [comment]
Closing in favor of #152
