### ISSUE TITLE
Provide demo credentials as an option

### ISSUE THREAD

**Issue by Haroenv** [algolia/create-instantsearch-app#290]
## The problem

> A concise description of why you want a new feature.

You want to quickly make a reproduction without leaking your API keys, you need to look up in the docs to find existing config which works properly.

## Solution

> A clear description of what you want to happen.

Have an option for demo credentials instead of any of the other questions.

## Implementation

> Do you have an idea how it could be implemented?

Let the user choose between entering credentials and attribute and a default working set

**Comment by quentin-sommer** [comment]
Working on this!
