### ISSUE TITLE
Proposal: add linting and prettier configurations

### ISSUE THREAD

**Issue by vvo** [algolia/create-instantsearch-app#34]
What do you think about adding by default the right linting and prettier configurations form https://github.com/algolia/eslint-config-algolia/?

**Comment by vvo** [comment]
+ [editorconfig](https://github.com/algolia/react-instantsearch/blob/master/.editorconfig)

**Comment by francoischalifour** [comment]
I'm not sure it's a great thing to force users to use our own conventions. I was wondering if we should add more tooling to the templates. If you think this is the right choice, we can add those.

**Comment by samouss** [comment]
Maybe not only ours, we can allow the user to pick a specific preset like our, Airbnb, ...
