### ISSUE TITLE
Generated InstantSearch.JS@3.5.3 referencing non existing CSS files

### ISSUE THREAD

**Issue by tkrugg** [algolia/create-instantsearch-app#409]
## Bug description

> Generated InstantSearch.JS@3.5.3 referencing non existing CSS files:
> -  https://cdn.jsdelivr.net/npm/instantsearch.js@3.5.3/dist/instantsearch.min.css
> - https://cdn.jsdelivr.net/npm/instantsearch.js@3.5.3/dist/instantsearch-theme-algolia.min.css 

## How to reproduce

> A list of the steps to reproduce the bug.

1. Run command:
```sh
create-instantsearch-app my-app
```
2. Select 
```sh
? InstantSearch template InstantSearch.js
? InstantSearch.js version 3.5.3
? Application ID latency
? Search API key 6be0576ff61c053d5f9a3225e2a90f76
? Index name instant_search
? Attributes to display: name
  Used to generate the default result template
```
3. See error
build and run generated app.

## Expected behavior

No reference to missing file. Probably a reference to instantsearch.css instead.

## Screenshots

N/A

## Environment

 - OS: MacOS / High Sierra
 - Create InstantSearch App version: 4.1.0

**Comment by francoischalifour** [comment]
The InstantSearch.js 3 template is available from [4.2.0](https://github.com/algolia/create-instantsearch-app/releases/tag/4.2.0). Before this version, only the v2 template existed.

Please upgrade your local version, or use `yarn create instantsearch-app my-app` to always use the latest versions and templates.
