### ISSUE TITLE
[PROPOSAL] Alias to cisa?

### ISSUE THREAD

**Issue by vvo** [algolia/create-instantsearch-app#41]
As for command line, should we alias `create-instantsearch-app` to `cisa`? So that I don't have to type this much :D.

(Actually this is only relevant when used as a globally installed binary, might no be that relevant when used with npm init)

**Comment by francoischalifour** [comment]
My take on this is that it's up to the user to create a bash alias `cisa` that links to `create-instantsearch-app`.

Besides, as you said, we recommend using the tool from the npm registry. It doesn't make sense to rely too heavily on a secondary binary name IMO.

**Comment by Haroenv** [comment]
Would expect a nicer short binary name than cisa, maybe “instantsearch” would be a nice alternative binary though

**Comment by vvo** [comment]
I am fine with the decision, thanks!
