### ISSUE TITLE
Create app fails for InstantSearch.js

### ISSUE THREAD

**Issue by benlower** [algolia/create-instantsearch-app#566]
## Bug description

Tried creating a new application using `npx create-instantsearch-app 'test'`

## How to reproduce

Try running `npx create-instantsearch-app 'test'`

Make the following selections:

- Use InstantSearch.js template
- Choose latest version (4.40.5)
- use the defaults for Application ID, Search API key, and Index name
- Choose an attribute to display

## Expected behavior

Expect the creation to work with no errors.

## Output in terminal

benlower@USA-M1P-BL algolia-org-chart-app % npx create-instantsearch-app 'test'
Need to install the following packages:
  create-instantsearch-app
Ok to proceed? (y) y
? The name of the application or widget test

Creating a new InstantSearch app in test.

? InstantSearch template InstantSearch.js
? InstantSearch.js version 4.40.5
? Application ID latency
? Search API key 6be0576ff61c053d5f9a3225e2a90f76
? Index name instant_search
? Attributes to display
  Used to generate the default result template 
? Attributes to display
  Used to filter the search interface Dynamic widgets

📦  Installing dependencies...

npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/benlower/Dropbox/Mac/Documents/GitHub/algolia-org-chart-app/test/node_modules/deasync
npm ERR! command failed
npm ERR! command sh -c node ./build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.0
npm ERR! gyp info using node@16.13.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/benlower/Dropbox/Mac/Documents/GitHub/algolia-org-chart-app/test/node_modules/deasync/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/benlower/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/benlower/Library/Caches/node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/benlower/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/benlower/Dropbox/Mac/Documents/GitHub/algolia-org-chart-app/test/node_modules/deasync',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.4.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/benlower/Dropbox/Mac/Documents/GitHub/algolia-org-chart-app/test/node_modules/deasync
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.4.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benlower/.npm/_logs/2022-05-14T20_46_53_124Z-debug.log

📦  Dependencies could not be installed.
Error: Command failed: npm install
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at install (/Users/benlower/.npm/_npx/9be8ac332fc6b44b/node_modules/create-instantsearch-app/src/tasks/node/install.js:18:5)
    at Object.create (/Users/benlower/.npm/_npx/9be8ac332fc6b44b/node_modules/create-instantsearch-app/src/api/index.js:44:17)
    at async run (/Users/benlower/.npm/_npx/9be8ac332fc6b44b/node_modules/create-instantsearch-app/src/cli/index.js:365:3) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 89979,
  stdout: null,
  stderr: null
}

Try to create the app without installing the dependencies:
  create-instantsearch-app test --no-installation

🛑  Aborting the app generation.

✨  Cleaning up /Users/benlower/Dropbox/Mac/Documents/GitHub/algolia-org-chart-app/test.

## Environment

 - OS: macOS Monterey 12.3.1
 - Create InstantSearch App version: ran from npx on May 14, 2022

**Comment by Haroenv** [comment]
Do you mind sending `/Users/benlower/.npm/_logs/2022-05-14T20_46_53_124Z-debug.log` as well @benlower ?

**Comment by benlower** [comment]
[2022-05-14T20_46_53_124Z-debug.log](https://github.com/algolia/create-instantsearch-app/files/8701330/2022-05-14T20_46_53_124Z-debug.log)

There's the log. I was able to get unblocked on the xcrun error by installing XCode toolkit via `xcode-select --install`.

Seems like adding that as a pre-requisite would make things more clear.
